name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  pipeline:
    uses: wstalmans1/cicd-workflows-tests/.github/workflows/reusable-frontend-deploy.yml@main
    with:
      pin-name-prefix: ssilearning.eth.limo
      node-version: '22'
      pnpm-version: '10'
    secrets: inherit
